#!/bin/bash

# create a file with gnuplot commands
gnuplot - &> /dev/null << EOF
set title "$(basename $PWD)"
set term png crop
set output 'disk-utilization.png'
set xdata time
set timefmt '%H:%M:%S'
set xlabel 'time'
set format x '%H:%M:%S'
set xtics rotate
set ylabel 'disk utilization'
plot [] [0:100] \\
'block_device' u 1:10 smooth csplines t 'disk utilization' with lines
EOF
