#!/bin/bash

# create a file with gnuplot commands
gnuplot - &> /dev/null << EOF
set term png crop
set output 'memory_utilization.png'
set xdata time
set timefmt '%H:%M:%S'
set xlabel 'time'
set format x '%H:%M:%S'
set xtics rotate
set ylabel 'memory utilization'
plot [] [0:100] \\
'memory' u 1:4 smooth csplines t 'memory utilization' with lines
EOF
