#!/bin/bash

# column heading for interrupts_summary
# 14:31:00   sum    intrs/sec

# create a file with gnuplot commands
gnuplot - &> /dev/null << EOF
set title "$(basename $PWD)"
set term png crop
set output 'interrupts.png'
set xdata time
set timefmt '%H:%M:%S'
set xlabel 'time'
set format x '%H:%M:%S'
set xtics rotate
set ylabel 'interrupts per second'
plot [] [0:] \\
'interrupt_summary' u 1:3 smooth csplines t 'interrupts/sec' with lines
EOF
