#!/bin/bash

# create a file with gnuplot commands
gnuplot - &> /dev/null << EOF
set title "$(basename $PWD)"
set term png crop
set output 'paging.png'
set xdata time
set timefmt '%H:%M:%S'
set xlabel 'time'
set format x '%H:%M:%S'
set xtics rotate
set ylabel 'memory pages'
plot [] [0:] \\
'paging' u 1:2 smooth csplines t 'memory pages read/sec' with lines, \\
'paging' u 1:3 smooth csplines t 'memory pages written/sec' with lines, \\
'paging' u 1:4 smooth csplines t 'minor faults/sec' with lines, \\
'paging' u 1:5 smooth csplines t 'major faults/sec' with lines
EOF
