#!/usr/bin/env python

"""
sargather

Copyright 2011 Paul Morgan
jumanjiman@gmail.com

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import subprocess
import optparse

global verbose
global FILE

# configure CLI parser
p = optparse.OptionParser (
description = 'Gather sar data over a specified interval',
prog = 'sargather',
version = 'sargather 0.1',
usage = '%prog [option]'
)

p.add_option('--file', '-f', dest="filename",
help="read data from FILE", metavar="FILE")

# parse user options
(options, args) = p.parse_args()
