#!/usr/bin/env python

"""
sargather

Copyright 2011 Paul Morgan
jumanjiman@gmail.com

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import subprocess # facilitate calls to bash
import optparse   # CLI option handling
import re         # regex
import string     # string functions
import sys        # system-level primitives, such as err
import os         # work with files, dirs, etc.

# defaults
output_dir = "/tmp"

def run_bash (cmd):
	"""
	Runs a command, returning the return code, stdout, and stderr as a tuple.
	NOT FOR USE WITH INTERACTIVE COMMANDS.
	"""

	try:
		proc=subprocess.Popen (cmd, 
			shell=True, 
			stdout=subprocess.PIPE,
			stderr=subprocess.PIPE,
			close_fds=True
			)
		data=proc.communicate()
		return (proc.returncode, data[0], data[1])
	except Exception, err:
		sys.stderr.write('error: %s\n' % str(err) )
		exit (1)

# configure and run CLI parser
p = optparse.OptionParser (
	description = 'Gather sar data over a specified interval',
	prog = 'sargather',
	usage = '%prog [option]'
	)

p.add_option('--file', '-f', dest="filename",
	help="read data from FILE", metavar="FILE")

p.add_option('--start', '-s', dest="start_time",
	help="START in HH:MM:SS",
	metavar="START")

p.add_option('--end', '-e', dest="end_time",
	help="END in HH:MM:SS",
	metavar="END")

p.add_option('--dir', '-d', dest="output_dir",
	help="DIR in which to save output data", 
	default=output_dir,
	metavar="DIR")

# parse user options
(options, args) = p.parse_args()

# sanity-check
if options.start_time is None or options.end_time is None:
	p.print_help()
	exit(1)

# construct basic sar options
sar_options = "-s " + options.start_time + " -e " + options.end_time
if options.filename is not None:
	sar_options += " -f " + options.filename

if not os.path.exists (options.output_dir):
	try:
		os.makedirs (options.output_dir)
	except Exception, err:
		sys.stderr.write('error: %s\n' % str(err) )
		exit (1)

sar_cmd="LANG=C sar -A " + sar_options
output = run_bash(sar_cmd)
print "%s" % output[1]
exit (output[0])
