#!/usr/bin/env python

"""
sargather

Copyright 2011 Paul Morgan
jumanjiman@gmail.com

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import subprocess
import optparse

global verbose
global FILE
global dir

# configure CLI parser
p = optparse.OptionParser (
	description = 'Gather sar data over a specified interval',
	prog = 'sargather',
	usage = '%prog [option]'
	)

p.add_option('--file', '-f', dest="filename",
	help="read data from FILE", metavar="FILE")

p.add_option('--start', '-s', dest="start_time",
	help="START in HH:MM:SS", metavar="START")

p.add_option('--end', '-e', dest="end_time",
	help="END in HH:MM:SS", metavar="END")

p.add_option('--dir', '-d', dest="dir",
	help="DIR in which to save output data (defaults to /tmp)", metavar="DIR")

# parse user options
(options, args) = p.parse_args()

